# Generated by Django 4.2.4 on 2023-08-18 14:28

import datetime
from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='content',
            field=froala_editor.fields.FroalaField(default=datetime.datetime(2023, 8, 18, 14, 28, 5, 219656, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
